# Generated by Django 4.0.4 on 2022-05-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afrinic20220424',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=20, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'afrinic_2022_04_24',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Afrinic20220425',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=20, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'afrinic_2022_04_25',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Afrinic20220505',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=20, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'afrinic_2022_05_05',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Afrinic20220507',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=20, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'afrinic_2022_05_07',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Afrinic20220509',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=20, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'afrinic_2022_05_09',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Afrinic20220510',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'afrinic_2022_05_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Afrinic20220522',
            fields=[
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'afrinic_2022_05_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apnic20220510',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'apnic_2022_05_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apnic20220522',
            fields=[
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'apnic_2022_05_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arin20220510',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'arin_2022_05_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arin20220522',
            fields=[
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'arin_2022_05_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsnIp20220504',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_block', models.CharField(blank=True, db_column='IP_block', max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('max_length', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'asn_ip_2022_05_04',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsnIp20220505',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_block', models.CharField(blank=True, db_column='IP_block', max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('max_length', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'asn_ip_2022_05_05',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsnIp20220507',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_block', models.CharField(blank=True, db_column='IP_block', max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('max_length', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'asn_ip_2022_05_07',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsnIp20220509',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_block', models.CharField(blank=True, db_column='IP_block', max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('max_length', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'asn_ip_2022_05_09',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsnIp20220510',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_block', models.CharField(blank=True, db_column='IP_block', max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('max_length', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'asn_ip_2022_05_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsnIp20220520',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_block', models.CharField(blank=True, db_column='IP_block', max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('max_length', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'asn_ip_2022_05_20',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsnIp20220521',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_block', models.CharField(blank=True, db_column='IP_block', max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('max_length', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'asn_ip_2022_05_21',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsnIpRipe20220522',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=10, null=True)),
                ('ip_block', models.CharField(blank=True, db_column='IP_block', max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('max_length', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'asn_ip_ripe_2022_05_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate20220504',
            fields=[
                ('cert_name', models.CharField(blank=True, db_column='Cert_name', max_length=100, null=True)),
                ('cert_uri', models.CharField(db_column='Cert_URI', max_length=200, primary_key=True, serialize=False)),
                ('auth_uri', models.CharField(blank=True, db_column='Auth_URI', max_length=200, null=True)),
                ('sub_uri', models.CharField(blank=True, db_column='Sub_URI', max_length=200, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'certificate_2022_05_04',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate20220505',
            fields=[
                ('cert_name', models.CharField(blank=True, db_column='Cert_name', max_length=100, null=True)),
                ('cert_uri', models.CharField(db_column='Cert_URI', max_length=200, primary_key=True, serialize=False)),
                ('auth_uri', models.CharField(blank=True, db_column='Auth_URI', max_length=200, null=True)),
                ('sub_uri', models.CharField(blank=True, db_column='Sub_URI', max_length=200, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'certificate_2022_05_05',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate20220507',
            fields=[
                ('cert_name', models.CharField(blank=True, db_column='Cert_name', max_length=100, null=True)),
                ('cert_uri', models.CharField(db_column='Cert_URI', max_length=200, primary_key=True, serialize=False)),
                ('auth_uri', models.CharField(blank=True, db_column='Auth_URI', max_length=200, null=True)),
                ('sub_uri', models.CharField(blank=True, db_column='Sub_URI', max_length=200, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'certificate_2022_05_07',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate20220509',
            fields=[
                ('cert_name', models.CharField(blank=True, db_column='Cert_name', max_length=100, null=True)),
                ('cert_uri', models.CharField(db_column='Cert_URI', max_length=200, primary_key=True, serialize=False)),
                ('auth_uri', models.CharField(blank=True, db_column='Auth_URI', max_length=200, null=True)),
                ('sub_uri', models.CharField(blank=True, db_column='Sub_URI', max_length=200, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'certificate_2022_05_09',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate20220510',
            fields=[
                ('cert_name', models.CharField(blank=True, db_column='Cert_name', max_length=100, null=True)),
                ('cert_uri', models.CharField(db_column='Cert_URI', max_length=200, primary_key=True, serialize=False)),
                ('auth_uri', models.CharField(blank=True, db_column='Auth_URI', max_length=200, null=True)),
                ('sub_uri', models.CharField(blank=True, db_column='Sub_URI', max_length=200, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'certificate_2022_05_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate20220520',
            fields=[
                ('cert_name', models.CharField(blank=True, db_column='Cert_name', max_length=100, null=True)),
                ('cert_uri', models.CharField(db_column='Cert_URI', max_length=200, primary_key=True, serialize=False)),
                ('auth_uri', models.CharField(blank=True, db_column='Auth_URI', max_length=200, null=True)),
                ('sub_uri', models.CharField(blank=True, db_column='Sub_URI', max_length=200, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'certificate_2022_05_20',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate20220521',
            fields=[
                ('cert_name', models.CharField(blank=True, db_column='Cert_name', max_length=100, null=True)),
                ('cert_uri', models.CharField(db_column='Cert_URI', max_length=200, primary_key=True, serialize=False)),
                ('auth_uri', models.CharField(blank=True, db_column='Auth_URI', max_length=200, null=True)),
                ('sub_uri', models.CharField(blank=True, db_column='Sub_URI', max_length=200, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'certificate_2022_05_21',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateRipe20220522',
            fields=[
                ('cert_name', models.CharField(blank=True, db_column='Cert_name', max_length=100, null=True)),
                ('cert_uri', models.CharField(db_column='Cert_URI', max_length=200, primary_key=True, serialize=False)),
                ('auth_uri', models.CharField(blank=True, db_column='Auth_URI', max_length=200, null=True)),
                ('sub_uri', models.CharField(blank=True, db_column='Sub_URI', max_length=200, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'certificate_ripe_2022_05_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lacnic20220510',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'lacnic_2022_05_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lacnic20220522',
            fields=[
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lacnic_2022_05_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ripencc20220510',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ripencc_2022_05_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ripencc20220522',
            fields=[
                ('uri', models.CharField(blank=True, db_column='URI', max_length=200, null=True)),
                ('asn', models.CharField(blank=True, db_column='ASN', max_length=30, null=True)),
                ('ip_pre', models.CharField(blank=True, db_column='IP_pre', max_length=50, null=True)),
                ('max_len', models.CharField(blank=True, db_column='Max_len', max_length=10, null=True)),
                ('not_before', models.CharField(blank=True, db_column='Not_Before', max_length=50, null=True)),
                ('not_after', models.CharField(blank=True, db_column='Not_After', max_length=50, null=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ripencc_2022_05_22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roa20220504',
            fields=[
                ('roa_name', models.CharField(blank=True, db_column='ROA_name', max_length=100, null=True)),
                ('roa_uri', models.CharField(db_column='ROA_URI', max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'roa_2022_05_04',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roa20220505',
            fields=[
                ('roa_name', models.CharField(blank=True, db_column='ROA_name', max_length=100, null=True)),
                ('roa_uri', models.CharField(db_column='ROA_URI', max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'roa_2022_05_05',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roa20220507',
            fields=[
                ('roa_name', models.CharField(blank=True, db_column='ROA_name', max_length=100, null=True)),
                ('roa_uri', models.CharField(db_column='ROA_URI', max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'roa_2022_05_07',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roa20220509',
            fields=[
                ('roa_name', models.CharField(blank=True, db_column='ROA_name', max_length=100, null=True)),
                ('roa_uri', models.CharField(db_column='ROA_URI', max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'roa_2022_05_09',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roa20220510',
            fields=[
                ('roa_name', models.CharField(blank=True, db_column='ROA_name', max_length=100, null=True)),
                ('roa_uri', models.CharField(db_column='ROA_URI', max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'roa_2022_05_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roa20220520',
            fields=[
                ('roa_name', models.CharField(blank=True, db_column='ROA_name', max_length=100, null=True)),
                ('roa_uri', models.CharField(db_column='ROA_URI', max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'roa_2022_05_20',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roa20220521',
            fields=[
                ('roa_name', models.CharField(blank=True, db_column='ROA_name', max_length=100, null=True)),
                ('roa_uri', models.CharField(db_column='ROA_URI', max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'roa_2022_05_21',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoaRipe20220522',
            fields=[
                ('roa_name', models.CharField(blank=True, db_column='ROA_name', max_length=100, null=True)),
                ('roa_uri', models.CharField(db_column='ROA_URI', max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'roa_ripe_2022_05_22',
                'managed': False,
            },
        ),
    ]
